<?php
$a=array('甲','乙','丙','丁','戊','己','庚','辛','壬','癸');
$b=array('子','丑','寅','卯','辰','巳','午','未','申','酉','戌','亥');
$year=(int)-10016;
$inputyear=(int)2022;
$up=(int)(abs($inputyear-$year)%60)%10;
$low=(int)(abs($inputyear-$year)%60)%12;
print($a[$up].$b[$low]."年");
?>
